# Generated by Django 2.2 on 2020-07-14 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dvt', models.CharField(choices=[('R', 'Router'), ('S', 'Switch'), ('F', 'Firewall'), ('SR', 'Servidor'), ('RW', 'Router WIFI'), ('ED', 'End Device')], max_length=2, verbose_name='Tipo de Dispositivos')),
                ('ipv4', models.GenericIPAddressField(protocol='IPv4', verbose_name='IPv4 De Acceso')),
                ('ipv6', models.GenericIPAddressField(protocol='IPv6', verbose_name='IPv6 De Acceso')),
                ('ssh', models.BooleanField(blank=True, null=True)),
                ('telnet', models.BooleanField(blank=True, null=True)),
                ('conf', models.FileField(blank=True, null=True, upload_to='media/')),
                ('conf_t', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hostname')),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('serial', models.CharField(blank=True, max_length=50, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.CharField(blank=True, max_length=50, null=True)),
                ('mascara', models.CharField(blank=True, choices=[('8', '255.0.0.0/8'), ('9', '255.128.0.0/9'), ('10', '255.192.0.0/10'), ('11', '255.224.0.0/11'), ('12', '255.240.0.0/12'), ('13', '255.248.0.0/13'), ('14', '255.252.0.0/14'), ('15', '255.254.0.0/15'), ('16', '255.255.0.0/16'), ('17', '255.255.128.0/17'), ('18', '255.255.192.0/18'), ('19', '255.255.224.0/19'), ('20', '255.255.240.0/20'), ('21', '255.255.248.0/21'), ('22', '255.255.252.0/22'), ('23', '255.255.254.0/23'), ('24', '255.255.255.0/24'), ('25', '255.255.255.128/25'), ('26', '255.255.255.192/26'), ('27', '255.255.255.224/27'), ('28', '255.255.255.240/28'), ('29', '255.255.255.248/29'), ('30', '255.255.255.252/30'), ('31', '255.255.255.254/31'), ('32', '255.255.255.255/32')], max_length=50, null=True)),
                ('direccion', models.IntegerField(blank=True, null=True, verbose_name='Numero de usuarios')),
                ('subredes', models.IntegerField(default=0, verbose_name='Numero de subredes')),
                ('reserv', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=50)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('ssh', models.BooleanField(blank=True, null=True)),
                ('telnet', models.BooleanField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Device', verbose_name='Usuario del Dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateTimeField(auto_created=True, auto_now=True)),
                ('usuario', models.CharField(max_length=50)),
                ('solicitud', models.CharField(choices=[('0', 'Falla de conexion'), ('1', 'Expansion de red'), ('2', 'Solicitud de IP reservada')], max_length=200)),
                ('descripcion', models.TextField()),
                ('completa', models.BooleanField(default=False)),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puerto', models.CharField(blank=True, max_length=50, null=True)),
                ('vlan', models.IntegerField(blank=True, default=1, null=True)),
                ('mac', models.CharField(blank=True, max_length=50, null=True)),
                ('ipv4', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IPv4')),
                ('ipv6', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6', verbose_name='IPv6')),
                ('actv', models.BooleanField(default=False)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Device', verbose_name='Puerto del Dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(blank=True, max_length=2500, null=True)),
                ('alerta', models.BooleanField()),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Device', verbose_name='Logs del Dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='IpReservada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IPv4 De Acceso')),
                ('ipv6', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6', verbose_name='IPv6 De Acceso')),
                ('mac', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Ubicacion', verbose_name='Ubicacion del Equipo'),
        ),
    ]
