# Generated by Django 2.2 on 2020-06-08 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dvt', models.CharField(choices=[('R', 'Router'), ('SW', 'Switch'), ('F', 'Firewall'), ('SR', 'Servidor'), ('RW', 'Router WIFI')], default='SW', max_length=2, verbose_name='Tipo de Dispositivos')),
                ('ipv4', models.GenericIPAddressField(protocol='IPv4', verbose_name='IPv4 De Acceso')),
                ('ipv6', models.GenericIPAddressField(protocol='IPv6', verbose_name='IPv6 De Acceso')),
                ('ssh', models.BooleanField()),
                ('telnet', models.BooleanField()),
                ('conf', models.FileField(upload_to='')),
                ('conf_t', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puerto', models.CharField(max_length=50)),
                ('vlan', models.IntegerField(default=1)),
                ('mac', models.CharField(max_length=50)),
                ('ipv4', models.GenericIPAddressField(protocol='IPv4', verbose_name='IPv4')),
                ('ipv6', models.GenericIPAddressField(protocol='IPv6', verbose_name='IPv6')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Device')),
            ],
        ),
    ]
