# Generated by Django 2.2 on 2020-07-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudes',
            name='completa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='creacion',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
