# Generated by Django 2.2 on 2020-06-08 02:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Device'),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='ipv4',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IPv4'),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='ipv6',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv6', verbose_name='IPv6'),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='mac',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='puerto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='vlan',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
