# Generated by Django 2.2 on 2020-07-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmento',
            name='subredes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Numero de subredes'),
        ),
    ]
