# Generated by Django 2.2 on 2020-06-09 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200607_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hostname'),
        ),
        migrations.AddField(
            model_name='device',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Ubicacion', verbose_name='Ubicacion del Equipo'),
        ),
        migrations.AddField(
            model_name='puerto',
            name='actv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='departamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='conf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='device',
            name='conf_t',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='dvt',
            field=models.CharField(choices=[('R', 'Router'), ('SW', 'Switch'), ('F', 'Firewall'), ('SR', 'Servidor'), ('RW', 'Router WIFI'), ('ED', 'End Device')], default='SW', max_length=2, verbose_name='Tipo de Dispositivos'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ipv4',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='IPv4 De Acceso'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ipv6',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv6', verbose_name='IPv6 De Acceso'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ssh',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='telnet',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='puerto',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Device', verbose_name='Puerto del Dispositivo'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='localidad',
            field=models.CharField(max_length=50),
        ),
    ]
