# Generated by Django 2.2 on 2020-06-15 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200608_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango', models.CharField(blank=True, max_length=50, null=True)),
                ('mascara', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.IntegerField(blank=True, null=True, verbose_name='Numero de usuarios')),
                ('subredes', models.IntegerField(verbose_name='Numero de subredes')),
                ('reserv', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('ssh', models.BooleanField(blank=True, null=True)),
                ('telnet', models.BooleanField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Device', verbose_name='Usuario del Dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(blank=True, max_length=2500, null=True)),
                ('alerta', models.BooleanField()),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Device', verbose_name='Logs del Dispositivo')),
            ],
        ),
    ]
