# Generated by Django 2.2 on 2020-07-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200717_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf', models.TextField()),
                ('devices', models.ManyToManyField(to='accounts.Device')),
            ],
        ),
    ]
