# Generated by Django 2.2 on 2020-07-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sendconf'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='clave',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Password conexion'),
        ),
        migrations.AddField(
            model_name='device',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuario de Acceso'),
        ),
    ]
