# Generated by Django 2.2 on 2020-07-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200718_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ipv4',
            field=models.GenericIPAddressField(help_text='192.168.0.1', protocol='IPv4', verbose_name='IPv4'),
        ),
    ]
